### ISSUE TITLE
Module Name Confusion

### ISSUE THREAD

**Issue by thecliguy** [jdhitsolutions/MySQLite#12]
The name of this module confuses me...

It seems to be a portmanteau of [MySQL](https://en.wikipedia.org/wiki/MySQL) and [SQLite](https://en.wikipedia.org/wiki/SQLite).

But from what I can gather, the project doesn't have anything to do with MySQL, only SQLite.

What is the meaning behind the module name?

**Comment by jdhitsolutions** [comment]
Since I am not a database person, I didn't think about the possible naming confusion. I started this module years ago when I was naming things like MyTasks and MyTickle. If it helps, think of this as a set of PowerShell tools for managing my SQLite database files.

**Comment by thecliguy** [comment]
Understood, thanks for clarifying. It's an unfortunate choice of name.
