### ISSUE TITLE
Questions about capabilities

### ISSUE THREAD

**Issue by PylotLight** [jdhitsolutions/MySQLite#19]
Sorry I didn't know where else to log this @jdhitsolutions :

- What version of SQLite is being used here, as I'm looking for the latest version which supports read and write of the DB at the same time.
- Is there an autoincrement feature for ID so I don't have to add an $i++ in the loop to set to ID?
- Is there a bulk copy or bulk transaction feature for large inserts?

**Comment by jdhitsolutions** [comment]
I updated the assembly to version1.0.117.0 [last month]( https://github.com/jdhitsolutions/MySQLite/releases/tag/v0.11.0) I have no idea what version supports the feature you are looking for.  I don't really know the answers to your other questions. Those would be language or syntax questions I'm not qualified to answer. You'll have to search for answers like [this](https://learn.microsoft.com/en-us/dotnet/standard/data/sqlite/bulk-insert) or this on [autoincrementing](https://www.sqlite.org/autoinc.html).

**Comment by PylotLight** [comment]
Thanks for your response.
I assumed the autoincrement and bulkcopy items needed to be added to the module as params or something as I haven't seen how to set that in the create table cmdlet, but will have another look, cheers.

[Lochy Wragg - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=207qes)	[207qes]

On March 28, 2023 at 12:53 GMT, Jeff Hicks ***@***.***> wrote:

I updated the assembly to version1.0.117.0 [last month](https://github.com/jdhitsolutions/MySQLite/releases/tag/v0.11.0) I have no idea what version supports the feature you are looking for. I don't really know the answers to your other questions. Those would be language or syntax questions I'm not qualified to answer. You'll have to search for answers like [this](https://learn.microsoft.com/en-us/dotnet/standard/data/sqlite/bulk-insert) or this on [autoincrementing](https://www.sqlite.org/autoinc.html).

**Comment by jdhitsolutions** [comment]
The module is for loading the assemblies and to abstract things like creating databases and tables. Using the database with sqlite queries is up to you.

**Comment by PylotLight** [comment]
Yep, but the autoincrement for example would be part of that module side for creating the tables, not the writing insert queries bit. But all good for now.
I assume you can't help with "WARNING: Exception calling "ExecuteNonQuery" with "0" argument(s): "SQL logic error
cannot start a transaction within a transaction""
I'm probably not using transactions properly. Will keep researching and close this issue soon

**Comment by jdhitsolutions** [comment]
I looked for an autoincrement feature when I first started this module,  After reading https://www.sqlite.org/autoinc.html I use the native ROWID.

**Comment by PylotLight** [comment]
@jdhitsolutions Apologies, did you have a small example of using that? As currently, I've set a PK on ID "Int" but it ends up empty if i don't specify it.
![image](https://user-images.githubusercontent.com/7006124/228695327-e3125caf-957c-49d0-8c99-6a7d88ea3538.png)
